name: Test and Coverage

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout source code

      - uses: actions-rs/toolchain@v1
        name: Install package manager
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/toolchain@v1
        name: Install code linter
        with:
          toolchain: nightly
          components: clippy
          override: true

      - uses: actions-rs/clippy-check@v1
        name: Run code linter 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - uses: actions-rs/cargo@v1
        name: Run unit test  
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'

      - id: coverage
        name: Generate code coverage report  
        uses: actions-rs/grcov@v0.1

      - uses: codecov/codecov-action@v2
        name: Upload code coverage report to Codecov
        with:
          files: ${{ steps.coverage.outputs.report }}
          flags: unittests 
          name: codecov-awsp
          fail_ci_if_error: true 
          verbose: true